stages:
  - image
  - analysis
  - build


.image: &image
  stage: image
  before_script:
    - docker info
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker pull "$IMAGE_TAG" || true
    - docker build --cache-from "$IMAGE_TAG" -t "$IMAGE_TAG" "scripts/docker/$IMAGE_NAME" || docker build --no-cache -t "$IMAGE_TAG" "scripts/docker/$IMAGE_NAME"
    - docker push "$IMAGE_TAG"
  tags:
    - dind
    - old

docker:mod-corba:ubuntu:
  <<: *image
  variables:
    IMAGE_NAME: ubuntu:16.04
    IMAGE_TAG: $CI_REGISTRY_IMAGE/$IMAGE_NAME

docker:mod-corba:fedora29:
  <<: *image
  variables:
    IMAGE_NAME: fedora:29
    IMAGE_TAG: $CI_REGISTRY_IMAGE/$IMAGE_NAME
  only:
    - master
    - triggers
    - schedules
    - web

docker:mod-corba:fedora30:
  <<: *image
  variables:
    IMAGE_NAME: fedora:30
    IMAGE_TAG: $CI_REGISTRY_IMAGE/$IMAGE_NAME
  only:
    - master
    - triggers
    - schedules
    - web

.ubuntu_16_04: &ubuntu_16_04
  image: "$CI_REGISTRY/fred/mod-corba/ubuntu:16.04"
  tags:
    - amd64
    - builder
    - linux

.fedora_29: &fedora_29
  image: "$CI_REGISTRY/fred/mod-corba/fedora:29"
  tags:
    - amd64
    - builder
    - linux

.fedora_30: &fedora_30
  image: "$CI_REGISTRY/fred/mod-corba/fedora:30"
  tags:
    - amd64
    - builder
    - linux


licensing:
  <<: *ubuntu_16_04
  variables:
    SRC_DIR: /usr/local/env
  stage: analysis
  before_script:
    - echo "\$SRC_DIR=$SRC_DIR"
    - echo "\$HOME=$HOME"
    - install -m 700 -d $HOME/.ssh
    - install -m 600 $SRC_DIR/{id_rsa,id_rsa.pub,known_hosts} $HOME/.ssh/
    - git clone git@gitlab.office.nic.cz:internal-tools/license-check.git --single-branch --depth 1
  script:
    - ./license-check/license-check.sh -v


build:ubuntu:amd64:
  <<: *ubuntu_16_04
  stage: build
  script:
    - echo "\$PWD=$PWD"
    - cmake .
    - make -j $(($(grep -c processor /proc/cpuinfo) / 2 + 1)) distcheck

build:fedora29:amd64:
  <<: *fedora_29
  stage: build
  script:
    - echo "\$PWD=$PWD"
    - cmake .
    - make -j $(($(grep -c processor /proc/cpuinfo) / 2 + 1)) distcheck
  only:
    - master
    - triggers
    - schedules
    - web

build:fedora30:amd64:
  <<: *fedora_30
  stage: build
  script:
    - echo "\$PWD=$PWD"
    - cmake .
    - make -j $(($(grep -c processor /proc/cpuinfo) / 2 + 1)) distcheck
  only:
    - master
    - triggers
    - schedules
    - web
